### ISSUE TITLE
System.json esmodules includes capitalized file of Satasupe.js which breaks on linux

### ISSUE THREAD

**Issue by Alarich** [AdmiralNyar/Satasupe-FoundryVTT#24]
Hey there!

This game system cannot be loaded on Linux environments because the esmodules call does not match the actual file path.
In system.json:
```
"esmodules": ["module/Satasupe.js"],
```

Actual path:
```
module/satasupe.js
```

Please fix the capitalization.

**Comment by AdmiralNyar** [comment]
Oh...
I wasn't aware of that.

I fixed it.
I appreciate your help resolving the problem.
